### PR TITLE
5.2 up

### PR DESCRIPTION
**Pull request by zarath**
Modifications to run on linux kernel >= 5.2

### CODE REVIEW

**Comment by dionisos2** [comment]
It didn’t work on my computer : 
> ~ > uname -a                                                                                                                                                                                   (base) 
> Linux archlinux 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux

Is there something special do to do to make it works ?
I would love to be able to use this driver again.

**Comment by zarath** [comment]
should build with make && make install && depmod -a

if kernel headers are available in /lib/modules/KVER/..

**Comment by dionisos2** [comment]
Just to be sure : The dkms way to install the driver explained in the README.md is no longer supported in this 5.2-up branch ? Or are both way equivalent ?

**Comment by zarath** [comment]
i didn't change the dkim version string
so i'm not sure if it works if it was already installed via dkms

**Comment by zarath** [comment]
I close this as it crashes.

**Pull request closed without merging**
